### ISSUE TITLE
ssl 에러 

### ISSUE THREAD

**Issue by VoltIcaRus** [acidpop/xpebot#32]
정말 계속 잘쓰고있던중에 문제가 생겨 해답을못찾아 여기에 남겨봅니다

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/telepot/__init__.py", line 1183, in get_from_telegram_server
    allowed_updates=allowed_upd)
  File "/usr/lib/python2.7/site-packages/telepot/__init__.py", line 1000, in getUpdates
    return self._api_request('getUpdates', _rectify(p))
  File "/usr/lib/python2.7/site-packages/telepot/__init__.py", line 491, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/lib/python2.7/site-packages/telepot/api.py", line 154, in request
    r = fn(*args, **kwargs)  # `fn` must be thread-safe
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 150, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /봇아이디/getUpdates (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

dsm 6.2.2 24922 최신버전을 설치하고부터 
이 에러가 뜹니다 전에 업데이트할때는 뜨지않고요
업데이트하고나서  telepot에러가 뜨길래 
python ./get-pip.py

pip install telepot BeautifulSoup psycopg2 Pillow psutil
를 다시해주어 설치했습니다 
https://api.telegram.org/bot토큰/getUpdates
을 nas나(curl -X GET) 메인컴에서 호출하면 정상적으로 
{"ok":true,"result":[]} 가 나와서 
방화벽 문제인가 싶지만 이것도아닌거같고.
봇은 문제없어보이고 어디가 문제인지 모르겠습니다 해외포럼봐도...
혹시 아시는부분이 있으신가요?
항상 평소엔 편하게받다 안되면 정말 불편해져버리는걸보면
xpebot은 정말필수품이네요..

저는 let's encrypt 와일드카드인증서를 acme.sh를 이용해 발급해서 사용하고있습니다.
참조
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
https://github.com/eternnoir/pyTelegramBotAPI/issues/528

**Comment by acidpop** [comment]
안녕하세요
저도 동일 증상이 나타나서 살펴 보고 있습니다

dsm 을 재설치를 해서 완벽한 해결 방법은 못드릴 수도 있어요 ㅠㅠ

**Comment by VoltIcaRus** [comment]
ssl인증서 문제인가 했는데 저만그런게 아닌가보군요 ㅜㅜ 
일단 저만그런게 아니라?? 다행입니다 ? 어디서나오는 문제인지 뒤져봐도 이것도 저것도아닌거같고 
ㅎㅎ 여튼 답변감사합니다

**Comment by acidpop** [comment]
Telepot 이슈 게시판을 보니 urllib 를 다운 그레이드 하라는 답변이 보이네요

pip install urllib3==1.24.1

저는 DSM 을 날려서 시도를 못해보네요 ㅠㅠ

**Comment by VoltIcaRus** [comment]
Traceback (most recent call last):
  File "/bin/pip", line 6, in <module>
    from pip._internal import main
  File "/usr/lib/python2.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/usr/lib/python2.7/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 20, in <module>
    from pip._internal.download import PipSession
  File "/usr/lib/python2.7/site-packages/pip/_internal/download.py", line 15, in <module>
    from pip._vendor import requests, six, urllib3
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/lib/python2.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 13, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "/usr/lib/python2.7/site-packages/asn1crypto/keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "/usr/lib/python2.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "/usr/lib/python2.7/site-packages/asn1crypto/_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "/usr/lib/python2.7/site-packages/asn1crypto/_perf/_big_num_ctypes.py", line 35, in <module>
    libcrypto_path = find_library(b'crypto' if sys.version_info < (3,) else 'crypto')
  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library crypto

이젠 암호화 오류..
으음.....
찾아보니 ipkg에서 gcc인지 먼지 설치해서 해결하라는데 모르겠습니다...
https://github.com/pypa/pip/issues/3588

pip install urllib3==1.24.1 을하면 위와같은 오류가 뜨고 이에 대해서 찾아보고있는데 시놀로지문제라는거같고..
다운그레이드만하면될거같았는데 다운그레이드가 안되니 모르겠습니다..

텔레팟 프로텍트가 끝났군요..? 대체가 있는진 모르겠네요

**Comment by acidpop** [comment]
음.. 이번에 DSM 이 업데이트 되면서 python 모듈 관련한것들도 뭔가 업데이트가 된건지 모르겠네요.

**Comment by acidpop** [comment]
안녕하세요
telepot 프로젝트가 중단되어서 Docker 형태의 synobot 을 새로 개발 하였습니다.

사용해보시고 불편한점이나 개선해야 할 점이 있다면 피드백 주세요~!

https://hub.docker.com/r/acidpop/synobot/

xpebot 의 많은 기능들을 대부분 삭제 하였고

기본 기능만 추가 하였습니다.

다운로드 스테이션 알림

마그넷 링크, 토렌트 파일 수신시 등록 기능

**Comment by VoltIcaRus** [comment]
정말 논외의 질문인데 
synobot의 스크립트를 수정해서 쓸순없을까요?
여태까지 텔레그램메세지를 제입맛에 맞는 말투로 바꿔서 써왔는데
도커라서 수정할방법이없네요.... 쓸때없는 질문이라 지송합니다;

**Comment by acidpop** [comment]
synobot 0.3 버전이 업데이트 되었습니다.

https://hub.docker.com/r/acidpop/synobot

위 링크에 안내 되어 있는 내용을 참고 하셔서 사용자가 원하는 문구로 수정이 가능합니다.

현재는 수동으로 해야 하나 다음 버전에는 좀 더 텔레그램 만으로 세팅 할 수 있는 방안을 구상중입니다.

**Comment by VoltIcaRus** [comment]
0.1버전에서 vi설치해서 직접 수정하였습니다
 도커는 처음이어서요 그걸 알고는 부끄러운질문인줄 알고 후다닥 삭제해버렸..
해당 파일찾는데 애먹었지만 여튼 하긴했습니다 그런데 수정도 해주신다니 정말 감사합니다
사용하시는dsm 정보가 적혀져있던데...
그리고 수정했을시 특수문자 ! 이런거는 마크다운 오류나서 전송이 되지않았습니다 0.2에서 수정하신?
리퀘스트 부분인거같기도..
항상감사합니다 돌아가서 해볼게요

**Comment by acidpop** [comment]
음.. 아마 제가 샘플로 입력 해둔 값일거에요
특수 문자는 mark down 모드로 메시지를 전송해서 발생하는 문제로 보이네요

저도 도커는 이번에 처음입니다 ^^;;;
많이 해메고 있어요
